#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Sat Feb 18 18:40:35 2023
#
import os 
import sys

import wx
from board import Board
from sudokuresolver import SudokuResolver

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

CLASSIC_SUDOKU_MIN_CLUES = 17

class CsFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        self.clues = {}
        # begin wxGlade: CsFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((510, 510))
        self.SetTitle("Classic Sudoku Resolver")
        self.SetMaxSize((510, 510))
        self.SetMinSize((510, 510))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetMinSize((500, 500))
        self.panel_1.SetMaxSize((500,500))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        header = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(header, 1, wx.BOTTOM | wx.EXPAND, 0)

        self.resolve = wx.Button(self.panel_1, wx.ID_ANY, "bt_resolve")
        header.Add(self.resolve, 0, 0, 0)

        self.board = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.board, 1, wx.EXPAND, 0)

        row_1 = wx.BoxSizer(wx.HORIZONTAL)
        self.board.Add(row_1, 1, wx.EXPAND, 0)

        col_1 = wx.GridSizer(3, 3, 1, 1)
        row_1.Add(col_1, 1, wx.EXPAND, 0)

        self.cell_11 = wx.TextCtrl(self.panel_1, 11, "")
        self.cell_11.SetMinSize((52, 52))
        self.cell_11.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_11.SetMaxLength(1)
        col_1.Add(self.cell_11, 0, 0, 0)

        self.cell_12 = wx.TextCtrl(self.panel_1, 12, "")
        self.cell_12.SetMinSize((52, 52))
        self.cell_12.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_12.SetMaxLength(1)
        col_1.Add(self.cell_12, 0, 0, 0)

        self.cell_13 = wx.TextCtrl(self.panel_1, 13, "")
        self.cell_13.SetMinSize((52, 52))
        self.cell_13.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_13.SetMaxLength(1)
        col_1.Add(self.cell_13, 0, 0, 0)

        self.cell_21 = wx.TextCtrl(self.panel_1, 21, "")
        self.cell_21.SetMinSize((52, 52))
        self.cell_21.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_21.SetMaxLength(1)
        col_1.Add(self.cell_21, 0, 0, 0)

        self.cell_22 = wx.TextCtrl(self.panel_1, 22, "")
        self.cell_22.SetMinSize((52, 52))
        self.cell_22.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_22.SetMaxLength(1)
        col_1.Add(self.cell_22, 0, 0, 0)

        self.cell_23 = wx.TextCtrl(self.panel_1, 23, "")
        self.cell_23.SetMinSize((52, 52))
        self.cell_23.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_23.SetMaxLength(1)
        col_1.Add(self.cell_23, 0, 0, 0)

        self.cell_31 = wx.TextCtrl(self.panel_1, 31, "")
        self.cell_31.SetMinSize((52, 52))
        self.cell_31.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_31.SetMaxLength(1)
        col_1.Add(self.cell_31, 0, 0, 0)

        self.cell_32 = wx.TextCtrl(self.panel_1, 32, "")
        self.cell_32.SetMinSize((52, 52))
        self.cell_32.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_32.SetMaxLength(1)
        col_1.Add(self.cell_32, 0, 0, 0)

        self.cell_33 = wx.TextCtrl(self.panel_1, 33, "")
        self.cell_33.SetMinSize((52, 52))
        self.cell_33.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_33.SetMaxLength(1)
        col_1.Add(self.cell_33, 0, 0, 0)

        col_2 = wx.GridSizer(3, 3, 1, 1)
        row_1.Add(col_2, 1, wx.EXPAND, 0)

        self.cell_14 = wx.TextCtrl(self.panel_1, 14, "")
        self.cell_14.SetMinSize((52, 52))
        self.cell_14.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_14.SetMaxLength(1)
        col_2.Add(self.cell_14, 0, 0, 0)

        self.cell_15 = wx.TextCtrl(self.panel_1, 15, "")
        self.cell_15.SetMinSize((52, 52))
        self.cell_15.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_15.SetMaxLength(1)
        col_2.Add(self.cell_15, 0, 0, 0)

        self.cell_16 = wx.TextCtrl(self.panel_1, 16, "")
        self.cell_16.SetMinSize((52, 52))
        self.cell_16.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_16.SetMaxLength(1)
        col_2.Add(self.cell_16, 0, 0, 0)

        self.cell_24 = wx.TextCtrl(self.panel_1, 24, "")
        self.cell_24.SetMinSize((52, 52))
        self.cell_24.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_24.SetMaxLength(1)
        col_2.Add(self.cell_24, 0, 0, 0)

        self.cell_25 = wx.TextCtrl(self.panel_1, 25, "")
        self.cell_25.SetMinSize((52, 52))
        self.cell_25.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_25.SetMaxLength(1)
        col_2.Add(self.cell_25, 0, 0, 0)

        self.cell_26 = wx.TextCtrl(self.panel_1, 26, "")
        self.cell_26.SetMinSize((52, 52))
        self.cell_26.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_26.SetMaxLength(1)
        col_2.Add(self.cell_26, 0, 0, 0)

        self.cell_34 = wx.TextCtrl(self.panel_1, 34, "")
        self.cell_34.SetMinSize((52, 52))
        self.cell_34.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_34.SetMaxLength(1)
        col_2.Add(self.cell_34, 0, 0, 0)

        self.cell_35 = wx.TextCtrl(self.panel_1, 35, "")
        self.cell_35.SetMinSize((52, 52))
        self.cell_35.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_35.SetMaxLength(1)
        col_2.Add(self.cell_35, 0, 0, 0)

        self.cell_36 = wx.TextCtrl(self.panel_1, 36, "")
        self.cell_36.SetMinSize((52, 52))
        self.cell_36.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_36.SetMaxLength(1)
        col_2.Add(self.cell_36, 0, 0, 0)

        col_3 = wx.GridSizer(3, 3, 1, 1)
        row_1.Add(col_3, 1, wx.EXPAND, 0)

        self.cell_17 = wx.TextCtrl(self.panel_1, 17, "")
        self.cell_17.SetMinSize((52, 52))
        self.cell_17.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_17.SetMaxLength(1)
        col_3.Add(self.cell_17, 0, 0, 0)

        self.cell_18 = wx.TextCtrl(self.panel_1, 18, "")
        self.cell_18.SetMinSize((52, 52))
        self.cell_18.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_18.SetMaxLength(1)
        col_3.Add(self.cell_18, 0, 0, 0)

        self.cell_19 = wx.TextCtrl(self.panel_1, 19, "")
        self.cell_19.SetMinSize((52, 52))
        self.cell_19.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_19.SetMaxLength(1)
        col_3.Add(self.cell_19, 0, 0, 0)

        self.cell_27 = wx.TextCtrl(self.panel_1, 27, "")
        self.cell_27.SetMinSize((52, 52))
        self.cell_27.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_27.SetMaxLength(1)
        col_3.Add(self.cell_27, 0, 0, 0)

        self.cell_28 = wx.TextCtrl(self.panel_1, 28, "")
        self.cell_28.SetMinSize((52, 52))
        self.cell_28.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_28.SetMaxLength(1)
        col_3.Add(self.cell_28, 0, 0, 0)

        self.cell_29 = wx.TextCtrl(self.panel_1, 29, "")
        self.cell_29.SetMinSize((52, 52))
        self.cell_29.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_29.SetMaxLength(1)
        col_3.Add(self.cell_29, 0, 0, 0)

        self.cell_37 = wx.TextCtrl(self.panel_1, 37, "")
        self.cell_37.SetMinSize((52, 52))
        self.cell_37.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_37.SetMaxLength(1)
        col_3.Add(self.cell_37, 0, 0, 0)

        self.cell_38 = wx.TextCtrl(self.panel_1, 38, "")
        self.cell_38.SetMinSize((52, 52))
        self.cell_38.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_38.SetMaxLength(1)
        col_3.Add(self.cell_38, 0, 0, 0)

        self.cell_39 = wx.TextCtrl(self.panel_1, 39, "")
        self.cell_39.SetMinSize((52, 52))
        self.cell_39.SetFont(wx.Font(32, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.cell_39.SetMaxLength(1)
        col_3.Add(self.cell_39, 0, 0, 0)

        row_2 = wx.BoxSizer(wx.HORIZONTAL)
        self.board.Add(row_2, 1, wx.ALL | wx.EXPAND, 1)

        row_2.Add((0, 0), 0, 0, 0)

        row_2.Add((0, 0), 0, 0, 0)

        row_2.Add((0, 0), 0, 0, 0)

        row_3 = wx.BoxSizer(wx.HORIZONTAL)
        self.board.Add(row_3, 1, wx.ALL | wx.EXPAND, 1)

        row_3.Add((0, 0), 0, 0, 0)

        row_3.Add((0, 0), 0, 0, 0)

        row_3.Add((0, 0), 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        self.Centre()

        self.Bind(wx.EVT_BUTTON, self.on_bt_resolve_pressed, self.resolve)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_11)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_12)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_13)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_21)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_22)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_23)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_31)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_32)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_33)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_14)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_15)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_16)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_24)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_25)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_26)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_34)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_35)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_36)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_17)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_18)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_19)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_27)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_28)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_29)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_37)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_38)
        self.Bind(wx.EVT_TEXT, self.on_txt, self.cell_39)
        # end wxGlade

    def on_bt_resolve_pressed(self, event):  # wxGlade: CsFrame.<event_handler>
        print("Event handler 'on_bt_resolve_pressed' called!")
        """
        validate that there are clues: min is 17 for classic sudoku
        """
        # print("abs path of current dir -->" + os.path.abspath("."))
        for p in sys.path:
            print("path --> "+ p)

        if len(self.clues.keys()) < CLASSIC_SUDOKU_MIN_CLUES:
            wx.MessageBox("Too few clues provided. Minimum expected for classic Sudoku is 17",
            "Error: invalid number of clues", wx.OK)
            print(f"Not enough clues provided: {len(self.clues.keys())}")
            event.Skip()
            return
        
        # start execution
        b = Board(self.clues)
        resolver = SudokuResolver(b)
        resolver.print()
        event.Skip()

    def on_txt(self, event):  # wxGlade: CsFrame.<event_handler>
        print("Event handler 'on_txt' called!")
        # print(type(event)) # wx._core.CommandEvent

        cell_id = event.GetId()
        value = event.GetString()
        print(f"Text entered in cell {str(cell_id)} -> {value}")

        if value == '':
            if cell_id in self.clues.keys():
                self.clues.pop(cell_id)
                print(f"Emptied cell {cell_id}")
        else:
            try:
                value_int = int(value)
                if value_int > 0 and value_int < 10:
                    self.clues[cell_id] = value
                    print(f"Entered value (cell -> val) {cell_id} -> {value}")
                else:
                    print(f"Invalid value: out of range: {value}")
            except ValueError:
                # could not parse to int
                print(f"Invalid value: not a number: {value}")
    
        event.Skip()

    def on_txt_enter(self, event):  # wxGlade: CsFrame.<event_handler>
        print("Event handler 'on_txt_enter' not implemented!")
        event.Skip()
# end of class CsFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = CsFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
